// <auto-generated />
using System;
using LightningLab2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LightningLab2.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260211182545_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("LightningLab2.Models.Book", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = "B001",
                            Status = 0,
                            Title = "Clean Code"
                        },
                        new
                        {
                            Id = "B002",
                            Status = 1,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = "B003",
                            Status = 0,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            Id = "B004",
                            Status = 2,
                            Title = "Refactoring"
                        },
                        new
                        {
                            Id = "B005",
                            Status = 0,
                            Title = "The C# Player's Guide"
                        });
                });

            modelBuilder.Entity("LightningLab2.Models.Checkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CheckoutDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Checkouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = "B001",
                            CheckoutDate = new DateTime(2026, 2, 4, 11, 25, 45, 112, DateTimeKind.Local).AddTicks(3935),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = "B002",
                            CheckoutDate = new DateTime(2026, 1, 28, 11, 25, 45, 116, DateTimeKind.Local).AddTicks(7042),
                            ReturnDate = new DateTime(2026, 2, 9, 11, 25, 45, 116, DateTimeKind.Local).AddTicks(7067),
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            BookId = "B003",
                            CheckoutDate = new DateTime(2026, 2, 8, 11, 25, 45, 116, DateTimeKind.Local).AddTicks(7140),
                            UserId = 5
                        });
                });

            modelBuilder.Entity("LightningLab2.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Fines")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fines = 5.00m,
                            IsBanned = false,
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            Id = 2,
                            Fines = 15.00m,
                            IsBanned = false,
                            Name = "Bob Smith"
                        },
                        new
                        {
                            Id = 3,
                            Fines = 0m,
                            IsBanned = true,
                            Name = "Charlie Brown"
                        },
                        new
                        {
                            Id = 4,
                            Fines = 0m,
                            IsBanned = false,
                            Name = "Diana Prince"
                        },
                        new
                        {
                            Id = 5,
                            Fines = 3.50m,
                            IsBanned = false,
                            Name = "Eve Wilson"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
